import XCTest
@testable import GitViewCore

final class PathClassifierTests: XCTestCase {
    func testRecognisesTestPaths() {
        for path in [
            "Tests/GitViewCoreTests/RiskModelTests.swift",
            "Tests/Foo.swift",
            "Sources/App/MyFeatureTests/Helper.swift",
            "Sources/App/ThingTest.swift",
            "Sources/App/TestHelpers.swift",
            "Sources/App/NetworkMock.swift",
        ] {
            XCTAssertTrue(PathClassifier.isTest(path: path), path)
        }
    }

    func testDoesNotFlagProductionCode() {
        for path in [
            "Sources/GitViewCore/RiskModel.swift",
            "Sources/NIOPosix/SocketChannel.swift",
            "Sources/App/Contest.swift",     // ends in "test" but not "Test"
            "Sources/Latest/Thing.swift",    // directory merely contains "test"
        ] {
            XCTAssertFalse(PathClassifier.isTest(path: path), path)
        }
    }
}

final class VendoredCodeTests: XCTestCase {
    func testRecognisesVendorDirectories() {
        for path in ["vendor/lib/a.c", "node_modules/pkg/index.js", "third_party/zlib/z.c",
                     "Pods/Alamofire/Source/A.swift", "app/dist/bundle.js", "deps/x/y.go"] {
            XCTAssertTrue(PathClassifier.isVendored(path: path), path)
        }
    }

    func testRecognisesGeneratedFilenames() {
        for path in ["web/app.min.js", "api/service.pb.go", "api/service_pb2.py",
                     "model/user.g.dart", "Forms/Main.Designer.cs", "grammar/src/parser.c",
                     "Sources/API.generated.swift"] {
            XCTAssertTrue(PathClassifier.isVendored(path: path), path)
        }
    }

    func testDoesNotFlagOrdinaryCode() {
        for path in ["Sources/App/Builder.swift", "src/main.rs", "lib/parser_helpers.c",
                     "app/distance.js", "src/vendoring.py"] {
            XCTAssertFalse(PathClassifier.isVendored(path: path), path)
        }
    }

    func testDetectsGeneratedHeaders() {
        XCTAssertTrue(PathClassifier.looksGenerated(header: "// Code generated by protoc. DO NOT EDIT.\npackage x"))
        XCTAssertTrue(PathClassifier.looksGenerated(header: "/* @generated */"))
        XCTAssertTrue(PathClassifier.looksGenerated(header: "# This file was generated automatically"))
        XCTAssertFalse(PathClassifier.looksGenerated(header: "// A hand-written parser\nfunc parse() {}"))
    }

    func testOnlyTheHeadOfAFileIsInspected() {
        // "generated" mentioned in prose far into a file is not a marker.
        let source = String(repeating: "// ordinary comment line\n", count: 200) + "// generated by hand, ironically"
        XCTAssertFalse(PathClassifier.looksGenerated(header: source))
    }
}

final class ImplausibleComplexityTests: XCTestCase {
    /// The threshold must sit in the measured gap: above every hand-written function seen,
    /// far below the generated one. If someone lowers it, real hotspots start vanishing.
    func testThresholdSitsInTheMeasuredGap() {
        XCTAssertGreaterThan(PathClassifier.implausibleComplexity, 130,
                             "tree-sitter's ts_query_cursor__advance is hand-written at 130")
        XCTAssertGreaterThan(PathClassifier.implausibleComplexity, 121,
                             "swift-nio's ByteBuffer.write is hand-written at 121")
        XCTAssertLessThan(PathClassifier.implausibleComplexity, 1298,
                          "swift-nio's generated llhttp parser is 1298")
    }
}
