import Foundation

/// Classifies source paths so the CLI and the app agree on what a test is.
public enum PathClassifier {
    /// Matches SwiftPM's `Tests/` convention, Xcode's `…Tests` group convention, and the
    /// common `FooTests.swift` / `FooTest.swift` file naming.
    public static func isTest(path: String) -> Bool {
        let components = path.split(separator: "/")
        for component in components.dropLast() {
            if component == "Tests" || component == "Test" { return true }
            if component.hasSuffix("Tests") { return true }
        }
        guard let file = components.last else { return false }
        let stem = file.hasSuffix(".swift") ? String(file.dropLast(6)) : String(file)
        return stem.hasSuffix("Tests") || stem.hasSuffix("Test")
            || stem.hasPrefix("Test") || stem.hasSuffix("Mock") || stem.hasSuffix("Fixtures")
    }

    /// Directories that hold code the repository did not write.
    ///
    /// Mirrors the common entries in Linguist's vendor list. Ranking vendored code by risk
    /// is noise: nobody in this repository is going to refactor it, and because generated
    /// parsers and bundles are enormous they otherwise dominate the hotspot list.
    static let vendorDirectories: Set<String> = [
        "vendor", "vendors", "third_party", "thirdparty", "3rdparty", "external", "externals",
        "node_modules", "bower_components", "pods", "carthage", "packages", "dist", "build",
        ".build", "deps", "submodules", "extern",
    ]

    /// Filename patterns that are conventionally machine-produced.
    static func hasGeneratedName(_ file: String) -> Bool {
        let lower = file.lowercased()
        if lower.hasSuffix(".min.js") || lower.hasSuffix(".min.css") { return true }
        if lower.hasSuffix(".pb.go") || lower.hasSuffix(".pb.cc") || lower.hasSuffix(".pb.h") { return true }
        if lower.hasSuffix("_pb2.py") || lower.hasSuffix("_pb2_grpc.py") { return true }
        if lower.hasSuffix(".g.dart") || lower.hasSuffix(".freezed.dart") { return true }
        if lower.hasSuffix(".designer.cs") || lower.hasSuffix(".generated.swift") { return true }
        if lower == "parser.c" || lower == "grammar.json" || lower == "node-types.json" { return true }
        return lower.contains(".generated.") || lower.contains("_generated.")
    }

    public static func isVendored(path: String) -> Bool {
        let components = path.split(separator: "/")
        for component in components.dropLast() where vendorDirectories.contains(component.lowercased()) {
            return true
        }
        guard let file = components.last else { return false }
        return hasGeneratedName(String(file))
    }

    /// A complexity no hand-written function plausibly reaches, so a file containing one
    /// is machine-generated even without a marker.
    ///
    /// Measured rather than guessed. Across swift-nio (13,549 units) and the tree-sitter
    /// repository (3,893 units) the complexity distribution is p50 1, p90 3, p99 9,
    /// p99.9 21, and the highest *hand-written* functions are 121 (swift-nio's HTTP
    /// encoder) and 130 (tree-sitter's query cursor). The only value above that is 1,298 —
    /// swift-nio's bundled llhttp parser, a 10,101-line generated state machine with no
    /// marker and no vendor directory in its path. 300 sits in the empty gap: more than
    /// twice anything human, a quarter of the generated one.
    public static let implausibleComplexity = 300

    /// Markers conventional tools write at the top of generated files. Only the first part
    /// of a file is inspected: a mention of "generated" deep inside a source file is prose,
    /// not a marker.
    public static func looksGenerated(header: String) -> Bool {
        let prefix = header.prefix(2048).lowercased()
        for marker in ["@generated", "do not edit", "don't edit", "automatically generated",
                       "auto-generated", "autogenerated", "generated by", "this file was generated",
                       "code generated by"] where prefix.contains(marker) {
            return true
        }
        return false
    }
}
